window.tsvSquadData = {
  defaultTeam: "team1",
  teams: {
    team1: {
      key: "team1",
      label: "1. Mannschaft",
      eyebrow: "Herren I",
      heroTitle: "Spielerkarten und Aufstellung.",
      heroLead: "Der Kader basiert auf der FuPa-Teamseite des TSV Hainsfarth, Stand 2026-04-30. Hier sieht man Spieler, Trainerteam und alle Daten gesammelt auf einer eigenen Seite.",
      heroBadge: "Herren I",
      seasonLabel: "Kader 2025/2026",
      seasonNote: "Mit Spielerkarten und Staff der ersten Mannschaft.",
      sourceDate: "2026-04-30",
      sourceLabel: "FuPa-Teamseite TSV Hainsfarth",
      sourceUrl: "https://www.fupa.net/team/tsv-hainsfarth-m1-2025-26",
      sectionEyebrow: "Herren I Kader",
      sectionTitle: "Alle Spieler auf einen Blick",
      sectionLead: "Alle Spielerkarten der ersten Mannschaft auf einen Blick mit Foto, Position und Leistungsdaten.",
      competition: "Kreisliga Donau Nord",
      players: [
        {
          id: 22912537,
          firstName: "Yannic",
          lastName: "Bederke",
          position: "Torwart",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 25,
          imageUrl: "https://image.fupa.net/player/1FzEc8cJ5nbe/"
        },
        {
          id: 23876282,
          firstName: "Thomas",
          lastName: "Grygar",
          position: "Torwart",
          jerseyNumber: null,
          matches: 3,
          goals: 0,
          flags: [],
          age: 39,
          imageUrl: "https://image.fupa.net/player/xucF1UJHPUr0/"
        },
        {
          id: 22912517,
          firstName: "Timo",
          lastName: "Haffelt",
          position: "Torwart",
          jerseyNumber: 1,
          matches: 0,
          goals: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/GHQMtdXIjctS/"
        },
        {
          id: 22912526,
          firstName: "Tobias",
          lastName: "Hoffmann",
          position: "Torwart",
          jerseyNumber: 1,
          matches: 0,
          goals: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/7RGg4VAzVof5/"
        },
        {
          id: 22912531,
          firstName: "Christoph",
          lastName: "Kolitsch",
          position: "Torwart",
          jerseyNumber: 1,
          matches: 17,
          goals: 0,
          flags: [],
          age: 27,
          imageUrl: "https://image.fupa.net/player/NcjbGLOfeOno/"
        },
        {
          id: 22912518,
          firstName: "Florian",
          lastName: "Angerer",
          position: "Abwehr",
          jerseyNumber: 14,
          matches: 16,
          goals: 1,
          flags: [],
          age: 31,
          imageUrl: "https://image.fupa.net/player/B6MovWSTWNfA/"
        },
        {
          id: 23876549,
          firstName: "Martin",
          lastName: "Bauer",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 6,
          goals: 1,
          flags: [],
          age: 35,
          imageUrl: "https://image.fupa.net/player/pzGb0PGI24aM/"
        },
        {
          id: 24158742,
          firstName: "Sven",
          lastName: "Großhauser",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [
            "new"
          ],
          age: 20,
          imageUrl: "https://image.fupa.net/player/f9p8kcYelk8b/"
        },
        {
          id: 23930560,
          firstName: "Florian",
          lastName: "Hensolt",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 7,
          goals: 0,
          flags: [],
          age: 32,
          imageUrl: "https://image.fupa.net/player/OKKsunKvilgu/"
        },
        {
          id: 22912522,
          firstName: "Jonas",
          lastName: "Meyer",
          position: "Abwehr",
          jerseyNumber: 11,
          matches: 5,
          goals: 0,
          flags: [],
          age: 24,
          imageUrl: "https://image.fupa.net/player/87Uybr9gtyRb/"
        },
        {
          id: 22912515,
          firstName: "Dennis",
          lastName: "Schröppel",
          position: "Abwehr",
          jerseyNumber: 3,
          matches: 16,
          goals: 0,
          flags: [],
          age: 30,
          imageUrl: "https://image.fupa.net/player/i2V87gpRuRu4/"
        },
        {
          id: 23766306,
          firstName: "Michael",
          lastName: "Seitz",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 10,
          goals: 0,
          flags: [],
          age: 37,
          imageUrl: "https://image.fupa.net/player/xsLtdyId1huZ/"
        },
        {
          id: 22912519,
          firstName: "Hannes",
          lastName: "Sitta",
          position: "Abwehr",
          jerseyNumber: 6,
          matches: 18,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/XNq2qEv3xKj0/"
        },
        {
          id: 23876554,
          firstName: "Reinhard",
          lastName: "Steinhoff",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 9,
          goals: 1,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/PVoBA3Y0y8ix/"
        },
        {
          id: 23766320,
          firstName: "Markus",
          lastName: "Straßner",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 4,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/K1kBuOat6XFS/"
        },
        {
          id: 22912527,
          firstName: "Benjamin",
          lastName: "Taglieber",
          position: "Abwehr",
          jerseyNumber: 4,
          matches: 17,
          goals: 0,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/U8YOFMSas8PA/"
        },
        {
          id: 23888201,
          firstName: "Luis",
          lastName: "Tremmel",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 7,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/3FcWKCuQ3oSk/"
        },
        {
          id: 22912525,
          firstName: "Simon",
          lastName: "Wiedemann",
          position: "Abwehr",
          jerseyNumber: 12,
          matches: 2,
          goals: 0,
          flags: [],
          age: 23,
          imageUrl: "https://image.fupa.net/player/edroiFk1cyLu/"
        },
        {
          id: 23793846,
          firstName: "Thomas",
          lastName: "Eberle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 8,
          goals: 0,
          flags: [],
          age: 38,
          imageUrl: "https://image.fupa.net/player/r7H9hLPYRN9t/"
        },
        {
          id: 22912532,
          firstName: "Silvan",
          lastName: "Egner",
          position: "Mittelfeld",
          jerseyNumber: 13,
          matches: 17,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/rdu8ocLq0xrB/"
        },
        {
          id: 24158750,
          firstName: "Maximilian",
          lastName: "Haas",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 24,
          imageUrl: "https://image.fupa.net/player/sWpostsVsvgB/"
        },
        {
          id: 22912520,
          firstName: "Nico",
          lastName: "Hensolt",
          position: "Mittelfeld",
          jerseyNumber: 21,
          matches: 15,
          goals: 5,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/UvsX5ItV5EjK/"
        },
        {
          id: 22912533,
          firstName: "David",
          lastName: "Hertle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 5,
          goals: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/2T8fRkQ9qpdU/"
        },
        {
          id: 22912536,
          firstName: "Silvan",
          lastName: "Hertle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 3,
          goals: 0,
          flags: [],
          age: 41,
          imageUrl: "https://image.fupa.net/player/xioCZmDrN9Ry/"
        },
        {
          id: 22912514,
          firstName: "Martin",
          lastName: "Hoffmann",
          position: "Mittelfeld",
          jerseyNumber: 8,
          matches: 13,
          goals: 0,
          flags: [],
          age: 32,
          imageUrl: "https://image.fupa.net/player/t5rand7jG9Of/"
        },
        {
          id: 22912528,
          firstName: "Tolga",
          lastName: "Kahveci",
          position: "Mittelfeld",
          jerseyNumber: 22,
          matches: 4,
          goals: 0,
          flags: [],
          age: 30,
          imageUrl: "https://image.fupa.net/player/yATiDSchGz4n/"
        },
        {
          id: 22912513,
          firstName: "Nico",
          lastName: "Leister",
          position: "Mittelfeld",
          jerseyNumber: 7,
          matches: 16,
          goals: 7,
          flags: [],
          age: 31,
          imageUrl: "https://image.fupa.net/player/NHGZwWK7iTIZ/"
        },
        {
          id: 24196503,
          firstName: "Hannes",
          lastName: "Meyer",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/tltkA3rh9xOJ/"
        },
        {
          id: 23832562,
          firstName: "Jannick",
          lastName: "Schwemmer",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/nBvZ9D2lXxnG/"
        },
        {
          id: 22912521,
          firstName: "Luca",
          lastName: "Stropek",
          position: "Mittelfeld",
          jerseyNumber: 9,
          matches: 17,
          goals: 9,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/ia55QkyqCBVS/"
        },
        {
          id: 22912534,
          firstName: "Garibaldi",
          lastName: "Üschner",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 5,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/"
        },
        {
          id: 22912529,
          firstName: "Jonas",
          lastName: "Babel",
          position: "Angriff",
          jerseyNumber: 16,
          matches: 0,
          goals: 0,
          flags: [],
          age: 27,
          imageUrl: "https://image.fupa.net/player/oyp9R2gd1iXL/"
        },
        {
          id: 22912516,
          firstName: "Jannik",
          lastName: "Gramm",
          position: "Angriff",
          jerseyNumber: 19,
          matches: 15,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/mnAFucSnqkRr/"
        },
        {
          id: 23766317,
          firstName: "Johannes",
          lastName: "Grün",
          position: "Angriff",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: 22,
          imageUrl: "https://image.fupa.net/player/kEhGlJIy7VaA/"
        },
        {
          id: 22912530,
          firstName: "Daniel",
          lastName: "Hensolt",
          position: "Angriff",
          jerseyNumber: 10,
          matches: 8,
          goals: 5,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/RZs3hqECiXOK/"
        },
        {
          id: 23818598,
          firstName: "Milos",
          lastName: "Pesut",
          position: "Angriff",
          jerseyNumber: null,
          matches: 3,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/6pxKXYYOFU0I/",
          hideImage: true
        }
      ],
      staff: [
        {
          id: 22912511,
          firstName: "Hans",
          lastName: "Golder",
          role: "Trainer",
          age: null,
          imageUrl: "https://image.fupa.net/player/CFpcgjjP2uKM/"
        },
        {
          id: 22912512,
          firstName: "Hannes",
          lastName: "Sitta",
          role: "Spielender Co-Trainer",
          age: 29,
          imageUrl: "https://image.fupa.net/player/XNq2qEv3xKj0/"
        },
        {
          id: 22912510,
          firstName: "Antonio",
          lastName: "Aglieri Rinella",
          role: "Physiotherapeut",
          age: null,
          imageUrl: "https://image.fupa.net/player/0Ea1kC8iBMZv/"
        },
        {
          id: 22912508,
          firstName: "Timo",
          lastName: "Haffelt",
          role: "Sportlicher Leiter",
          age: 33,
          imageUrl: "https://image.fupa.net/player/GHQMtdXIjctS/"
        },
        {
          id: 22912509,
          firstName: "Holger",
          lastName: "Meyr",
          role: "Sportlicher Leiter",
          age: 50,
          imageUrl: "https://image.fupa.net/player/aWZKd1kso7Aw/"
        }
      ]
    },
    team2: {
      key: "team2",
      label: "2. Mannschaft",
      eyebrow: "Herren II",
      heroTitle: "Spielerkarten und Aufstellung.",
      heroLead: "Der Kader basiert auf der FuPa-Teamseite des TSV Hainsfarth II, Stand 2026-04-30. Hier sieht man Spieler, Trainerteam und alle Daten gesammelt auf einer eigenen Seite.",
      heroBadge: "Herren II",
      seasonLabel: "Kader 2025/2026",
      seasonNote: "Mit Spielerkarten und Staff der zweiten Mannschaft.",
      sourceDate: "2026-04-30",
      sourceLabel: "FuPa-Teamseite TSV Hainsfarth II",
      sourceUrl: "https://www.fupa.net/team/tsv-hainsfarth-m2-2025-26",
      sectionEyebrow: "Herren II Kader",
      sectionTitle: "Alle Spieler auf einen Blick",
      sectionLead: "Alle Spielerkarten der zweiten Mannschaft auf einen Blick mit Foto, Position und Leistungsdaten.",
      competition: "Kreisliga Nord Res.",
      players: [
        {
          id: 22918365,
          firstName: "Yannic",
          lastName: "Bederke",
          position: "Torwart",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 25,
          imageUrl: "https://image.fupa.net/player/1FzEc8cJ5nbe/"
        },
        {
          id: 22918351,
          firstName: "Tobias",
          lastName: "Hoffmann",
          position: "Torwart",
          jerseyNumber: 22,
          matches: 1,
          goals: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/7RGg4VAzVof5/"
        },
        {
          id: 22918374,
          firstName: "Daniel",
          lastName: "Neuf",
          position: "Torwart",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/UwoPq0Eo8950/"
        },
        {
          id: 22918361,
          firstName: "Martin",
          lastName: "Bauer",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 35,
          imageUrl: "https://image.fupa.net/player/pzGb0PGI24aM/"
        },
        {
          id: 22918364,
          firstName: "Jakob",
          lastName: "Friedel",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 20,
          imageUrl: "https://image.fupa.net/player/tgn1Zjs4AiPh/"
        },
        {
          id: 22918363,
          firstName: "Sven",
          lastName: "Großhauser",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [],
          age: 20,
          imageUrl: "https://image.fupa.net/player/f9p8kcYelk8b/"
        },
        {
          id: 22918372,
          firstName: "Stefan",
          lastName: "Randi",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/2lJhGKIJi51y/"
        },
        {
          id: 22918355,
          firstName: "Michael",
          lastName: "Seitz",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 37,
          imageUrl: "https://image.fupa.net/player/xsLtdyId1huZ/"
        },
        {
          id: 22918377,
          firstName: "Reinhard",
          lastName: "Steinhoff",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 3,
          goals: 1,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/PVoBA3Y0y8ix/"
        },
        {
          id: 22918350,
          firstName: "Markus",
          lastName: "Straßner",
          position: "Abwehr",
          jerseyNumber: 13,
          matches: 2,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/K1kBuOat6XFS/"
        },
        {
          id: 22918367,
          firstName: "Daniel",
          lastName: "Taglieber",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/VEEUAj0mMeo3/"
        },
        {
          id: 22918376,
          firstName: "Luis",
          lastName: "Tremmel",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/3FcWKCuQ3oSk/"
        },
        {
          id: 24217078,
          firstName: "Simon",
          lastName: "Wiedemann",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [
            "new"
          ],
          age: 23,
          imageUrl: "https://image.fupa.net/player/edroiFk1cyLu/"
        },
        {
          id: 22918356,
          firstName: "Silvan",
          lastName: "Egner",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/rdu8ocLq0xrB/"
        },
        {
          id: 22918357,
          firstName: "Maximilian",
          lastName: "Haas",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [],
          age: 24,
          imageUrl: "https://image.fupa.net/player/sWpostsVsvgB/"
        },
        {
          id: 22918366,
          firstName: "Nico",
          lastName: "Hensolt",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/UvsX5ItV5EjK/"
        },
        {
          id: 22918349,
          firstName: "Silvan",
          lastName: "Hertle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 1,
          flags: [],
          age: 41,
          imageUrl: "https://image.fupa.net/player/xioCZmDrN9Ry/"
        },
        {
          id: 22918371,
          firstName: "Enrike",
          lastName: "Just",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/2XXzSq8yq06t/"
        },
        {
          id: 22918375,
          firstName: "Tolga",
          lastName: "Kahveci",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 30,
          imageUrl: "https://image.fupa.net/player/yATiDSchGz4n/"
        },
        {
          id: 22918379,
          firstName: "Nico",
          lastName: "Leister",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 31,
          imageUrl: "https://image.fupa.net/player/NHGZwWK7iTIZ/"
        },
        {
          id: 22918380,
          firstName: "Matthias",
          lastName: "Marx",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: 25,
          imageUrl: "https://image.fupa.net/player/1ythLl3TRhE4/"
        },
        {
          id: 22918360,
          firstName: "Hannes",
          lastName: "Meyer",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/tltkA3rh9xOJ/"
        },
        {
          id: 22918354,
          firstName: "Daniel",
          lastName: "Oesterle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 38,
          imageUrl: "https://image.fupa.net/player/GYLDnPyJEvgm/"
        },
        {
          id: 22918358,
          firstName: "Stefan",
          lastName: "Reichert",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 35,
          imageUrl: "https://image.fupa.net/player/OWGsZeMRx9fC/"
        },
        {
          id: 22918353,
          firstName: "Leon",
          lastName: "Seefried",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/AYVVnG7hPQJW/"
        },
        {
          id: 22918373,
          firstName: "Garibaldi",
          lastName: "Üschner",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/"
        },
        {
          id: 22918368,
          firstName: "Daniel",
          lastName: "Wiedemann",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/"
        },
        {
          id: 22918362,
          firstName: "Jonas",
          lastName: "Babel",
          position: "Angriff",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 27,
          imageUrl: "https://image.fupa.net/player/oyp9R2gd1iXL/"
        },
        {
          id: 22918352,
          firstName: "Jannik",
          lastName: "Gramm",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 1,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/mnAFucSnqkRr/"
        },
        {
          id: 22918369,
          firstName: "Johannes",
          lastName: "Grün",
          position: "Angriff",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          flags: [],
          age: 22,
          imageUrl: "https://image.fupa.net/player/kEhGlJIy7VaA/"
        },
        {
          id: 22918370,
          firstName: "Daniel",
          lastName: "Hensolt",
          position: "Angriff",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/RZs3hqECiXOK/"
        },
        {
          id: 22918378,
          firstName: "Simon",
          lastName: "Meyer",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [],
          age: 23,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/"
        },
        {
          id: 24181783,
          firstName: "Milos",
          lastName: "Pesut",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          flags: [
            "new"
          ],
          age: null,
          imageUrl: "https://image.fupa.net/player/6pxKXYYOFU0I/",
          hideImage: true
        },
        {
          id: 22918359,
          firstName: "Christoph",
          lastName: "Seitz",
          position: "Angriff",
          jerseyNumber: 14,
          matches: 2,
          goals: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/9Y7qdRHRTSTj/"
        }
      ],
      staff: [
        {
          id: 22918346,
          firstName: "Daniel",
          lastName: "Fackler",
          role: "Trainer",
          age: 33,
          imageUrl: "https://image.fupa.net/player/Ge1tFpMwYc6M/"
        },
        {
          id: 22918347,
          firstName: "Stefan",
          lastName: "Randi",
          role: "Trainer",
          age: 34,
          imageUrl: "https://image.fupa.net/player/2lJhGKIJi51y/"
        },
        {
          id: 22918348,
          firstName: "Antonio",
          lastName: "Aglieri Rinella",
          role: "Physiotherapeut",
          age: null,
          imageUrl: "https://image.fupa.net/player/0Ea1kC8iBMZv/"
        }
      ]
    }
  }
};
