window.tsvSquadData = {
  defaultTeam: "team1",
  teams: {
    team1: {
      key: "team1",
      label: "1. Mannschaft",
      eyebrow: "Herren I",
      heroTitle: "Spielerkarten und Aufstellung.",
      heroLead: "Der Kader basiert auf der FuPa-Teamseite des TSV Hainsfarth, Stand 2026-07-06. Hier sieht man Spieler, Trainerteam und alle Daten gesammelt auf einer eigenen Seite.",
      heroBadge: "Herren I",
      seasonLabel: "Kader 2025/2026",
      seasonNote: "Mit Spielerkarten und Staff der ersten Mannschaft.",
      sourceDate: "2026-07-06",
      sourceLabel: "FuPa-Teamseite TSV Hainsfarth",
      sourceUrl: "https://www.fupa.net/team/tsv-hainsfarth-m1-2025-26",
      sectionEyebrow: "Herren I Kader",
      sectionTitle: "Alle Spieler auf einen Blick",
      sectionLead: "Alle Spielerkarten der ersten Mannschaft auf einen Blick mit Foto, Position und Leistungsdaten.",
      competition: "Kreisliga Donau Nord",
      players: [
        {
          id: 22912537,
          slug: "nv-yannic-bederke-1578512",
          firstName: "Yannic",
          lastName: "Bederke",
          position: "Torwart",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 24,
          imageUrl: "https://image.fupa.net/player/1FzEc8cJ5nbe/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23876282,
          slug: "nv-thomas-grygar-446455",
          firstName: "Thomas",
          lastName: "Grygar",
          position: "Torwart",
          jerseyNumber: null,
          matches: 3,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: 38,
          imageUrl: "https://image.fupa.net/player/xucF1UJHPUr0/",
          yellowCards: 1,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912517,
          slug: "timo-haffelt-446462",
          firstName: "Timo",
          lastName: "Haffelt",
          position: "Torwart",
          jerseyNumber: 1,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 32,
          imageUrl: "https://image.fupa.net/player/GHQMtdXIjctS/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912526,
          slug: "tobias-hoffmann-446453",
          firstName: "Tobias",
          lastName: "Hoffmann",
          position: "Torwart",
          jerseyNumber: 1,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/UkSdfSE85OZX/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912531,
          slug: "christoph-kolitsch-686023",
          firstName: "Christoph",
          lastName: "Kolitsch",
          position: "Torwart",
          jerseyNumber: 1,
          matches: 23,
          goals: 0,
          assists: 0,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/NcjbGLOfeOno/",
          yellowCards: 3,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 2
        },
        {
          id: 22912518,
          slug: "florian-angerer-490737",
          firstName: "Florian",
          lastName: "Angerer",
          position: "Abwehr",
          jerseyNumber: 14,
          matches: 22,
          goals: 1,
          assists: 0,
          flags: [],
          age: 30,
          imageUrl: "https://image.fupa.net/player/B6MovWSTWNfA/",
          yellowCards: 0,
          yellowRedCards: 1,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23876549,
          slug: "martin-bauer-25332",
          firstName: "Martin",
          lastName: "Bauer",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 9,
          goals: 1,
          assists: 0,
          flags: [
            "new"
          ],
          age: 34,
          imageUrl: "https://image.fupa.net/player/pzGb0PGI24aM/",
          yellowCards: 1,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 24158742,
          slug: "sven-grosshauser-2188489",
          firstName: "Sven",
          lastName: "Großhauser",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: 19,
          imageUrl: "https://image.fupa.net/player/f9p8kcYelk8b/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23930560,
          slug: "florian-hensolt-446456",
          firstName: "Florian",
          lastName: "Hensolt",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 10,
          goals: 0,
          assists: 1,
          flags: [
            "new"
          ],
          age: 31,
          imageUrl: "https://image.fupa.net/player/OKKsunKvilgu/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912522,
          slug: "jonas-meyer-1272329",
          firstName: "Jonas",
          lastName: "Meyer",
          position: "Abwehr",
          jerseyNumber: 11,
          matches: 6,
          goals: 0,
          assists: 0,
          flags: [],
          age: 23,
          imageUrl: "https://image.fupa.net/player/87Uybr9gtyRb/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 24263645,
          slug: "felix-schmidt-379378",
          firstName: "Felix",
          lastName: "Schmidt",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 1,
          flags: [
            "new"
          ],
          age: 33,
          imageUrl: "https://image.fupa.net/player/psCGs1GRIaJU/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912515,
          slug: "dennis-schroeppel-446476",
          firstName: "Dennis",
          lastName: "Schröppel",
          position: "Abwehr",
          jerseyNumber: 3,
          matches: 22,
          goals: 0,
          assists: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/i2V87gpRuRu4/",
          yellowCards: 7,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23766306,
          slug: "michael-seitz-179998",
          firstName: "Michael",
          lastName: "Seitz",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 13,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: 36,
          imageUrl: "https://image.fupa.net/player/xsLtdyId1huZ/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912519,
          slug: "hannes-sitta-490765",
          firstName: "Hannes",
          lastName: "Sitta",
          position: "Abwehr",
          jerseyNumber: 6,
          matches: 24,
          goals: 0,
          assists: 3,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/XNq2qEv3xKj0/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23876554,
          slug: "reinhard-steinhoff-2426849",
          firstName: "Reinhard",
          lastName: "Steinhoff",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 12,
          goals: 2,
          assists: 0,
          flags: [
            "new"
          ],
          age: null,
          imageUrl: "https://image.fupa.net/player/PVoBA3Y0y8ix/",
          yellowCards: 0,
          yellowRedCards: 1,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23766320,
          slug: "markus-strassner-979156",
          firstName: "Markus",
          lastName: "Straßner",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 5,
          goals: 0,
          assists: 0,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/K1kBuOat6XFS/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912527,
          slug: "benjamin-taglieber-1484000",
          firstName: "Benjamin",
          lastName: "Taglieber",
          position: "Abwehr",
          jerseyNumber: 4,
          matches: 22,
          goals: 0,
          assists: 1,
          flags: [],
          age: 25,
          imageUrl: "https://image.fupa.net/player/U8YOFMSas8PA/",
          yellowCards: 6,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23888201,
          slug: "luis-tremmel-2365356",
          firstName: "Luis",
          lastName: "Tremmel",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 10,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: null,
          imageUrl: "https://image.fupa.net/player/3FcWKCuQ3oSk/",
          yellowCards: 1,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912525,
          slug: "simon-wiedemann-1913958",
          firstName: "Simon",
          lastName: "Wiedemann",
          position: "Abwehr",
          jerseyNumber: 12,
          matches: 7,
          goals: 0,
          assists: 0,
          flags: [],
          age: 22,
          imageUrl: "https://image.fupa.net/player/edroiFk1cyLu/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23793846,
          slug: "thomas-eberle-446465",
          firstName: "Thomas",
          lastName: "Eberle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 8,
          goals: 0,
          assists: 0,
          flags: [],
          age: 37,
          imageUrl: "https://image.fupa.net/player/r7H9hLPYRN9t/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912532,
          slug: "silvan-egner-485772",
          firstName: "Silvan",
          lastName: "Egner",
          position: "Mittelfeld",
          jerseyNumber: 13,
          matches: 23,
          goals: 0,
          assists: 2,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/rdu8ocLq0xrB/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 24158750,
          slug: "maximilian-haas-1788604",
          firstName: "Maximilian",
          lastName: "Haas",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 23,
          imageUrl: "https://image.fupa.net/player/sWpostsVsvgB/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912520,
          slug: "nico-hensolt-108824",
          firstName: "Nico",
          lastName: "Hensolt",
          position: "Mittelfeld",
          jerseyNumber: 21,
          matches: 18,
          goals: 11,
          assists: 4,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/UvsX5ItV5EjK/",
          yellowCards: 3,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 4
        },
        {
          id: 22912533,
          slug: "david-hertle-196590",
          firstName: "David",
          lastName: "Hertle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 5,
          goals: 0,
          assists: 2,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/2T8fRkQ9qpdU/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912536,
          slug: "silvan-hertle-179994",
          firstName: "Silvan",
          lastName: "Hertle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 3,
          goals: 0,
          assists: 0,
          flags: [],
          age: 40,
          imageUrl: "https://image.fupa.net/player/xioCZmDrN9Ry/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912514,
          slug: "martin-hoffmann-350462",
          firstName: "Martin",
          lastName: "Hoffmann",
          position: "Mittelfeld",
          jerseyNumber: 8,
          matches: 13,
          goals: 0,
          assists: 1,
          flags: [],
          age: 31,
          imageUrl: "https://image.fupa.net/player/t5rand7jG9Of/",
          yellowCards: 3,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912528,
          slug: "tolga-kahveci-78585",
          firstName: "Tolga",
          lastName: "Kahveci",
          position: "Mittelfeld",
          jerseyNumber: 22,
          matches: 4,
          goals: 0,
          assists: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/yATiDSchGz4n/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912513,
          slug: "nico-leister-179995",
          firstName: "Nico",
          lastName: "Leister",
          position: "Mittelfeld",
          jerseyNumber: 7,
          matches: 21,
          goals: 10,
          assists: 2,
          flags: [],
          age: 30,
          imageUrl: "https://image.fupa.net/player/NHGZwWK7iTIZ/",
          yellowCards: 10,
          yellowRedCards: 1,
          redCards: 0,
          teamOfWeek: 2
        },
        {
          id: 24196503,
          slug: "hannes-meyer-2071267",
          firstName: "Hannes",
          lastName: "Meyer",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/tltkA3rh9xOJ/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23832562,
          slug: "jannick-schwemmer-977973",
          firstName: "Jannick",
          lastName: "Schwemmer",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: 28,
          imageUrl: "https://image.fupa.net/player/nBvZ9D2lXxnG/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912521,
          slug: "luca-stropek-1518313",
          firstName: "Luca",
          lastName: "Stropek",
          position: "Mittelfeld",
          jerseyNumber: 9,
          matches: 22,
          goals: 13,
          assists: 11,
          flags: [],
          age: 25,
          imageUrl: "https://image.fupa.net/player/ia55QkyqCBVS/",
          yellowCards: 3,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 5
        },
        {
          id: 22912534,
          slug: "garibaldi-ueschner-2346918",
          firstName: "Garibaldi",
          lastName: "Üschner",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 7,
          goals: 0,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912529,
          slug: "nv-jonas-babel-2188485",
          firstName: "Jonas",
          lastName: "Babel",
          position: "Angriff",
          jerseyNumber: 16,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/oyp9R2gd1iXL/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912516,
          slug: "jannik-gramm-497501",
          firstName: "Jannik",
          lastName: "Gramm",
          position: "Angriff",
          jerseyNumber: 19,
          matches: 20,
          goals: 1,
          assists: 3,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/96zo0sWPSF2n/",
          yellowCards: 6,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23766317,
          slug: "johannes-gruen-2240299",
          firstName: "Johannes",
          lastName: "Grün",
          position: "Angriff",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: 21,
          imageUrl: "https://image.fupa.net/player/kEhGlJIy7VaA/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22912530,
          slug: "daniel-hensolt-112807",
          firstName: "Daniel",
          lastName: "Hensolt",
          position: "Angriff",
          jerseyNumber: 10,
          matches: 12,
          goals: 7,
          assists: 9,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/RZs3hqECiXOK/",
          yellowCards: 1,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 4
        },
        {
          id: 24513360,
          slug: "simon-meyer-2438423",
          firstName: "Simon",
          lastName: "Meyer",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [],
          age: 22,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 23818598,
          slug: "milos-pesut-1130534",
          firstName: "Milos",
          lastName: "Pesut",
          position: "Angriff",
          jerseyNumber: null,
          matches: 3,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: null,
          imageUrl: "https://image.fupa.net/player/6pxKXYYOFU0I/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0,
          hideImage: true
        }
      ],
      staff: [
        {
          id: 22912511,
          slug: "hans-golder-532156",
          firstName: "Hans",
          lastName: "Golder",
          role: "Trainer",
          age: null,
          imageUrl: "https://image.fupa.net/player/CFpcgjjP2uKM/"
        },
        {
          id: 22912512,
          slug: "hannes-sitta-490765",
          firstName: "Hannes",
          lastName: "Sitta",
          role: "Spielender Co-Trainer",
          age: 28,
          imageUrl: "https://image.fupa.net/player/XNq2qEv3xKj0/"
        },
        {
          id: 22912510,
          slug: "nv-antonio-aglieri-rinella-362054",
          firstName: "Antonio",
          lastName: "Aglieri Rinella",
          role: "Physiotherapeut",
          age: null,
          imageUrl: "https://image.fupa.net/player/0Ea1kC8iBMZv/"
        },
        {
          id: 22912508,
          slug: "timo-haffelt-446462",
          firstName: "Timo",
          lastName: "Haffelt",
          role: "Sportlicher Leiter",
          age: 32,
          imageUrl: "https://image.fupa.net/player/GHQMtdXIjctS/"
        },
        {
          id: 22912509,
          slug: "nv-holger-meyr-446469",
          firstName: "Holger",
          lastName: "Meyr",
          role: "Sportlicher Leiter",
          age: 50,
          imageUrl: "https://image.fupa.net/player/aWZKd1kso7Aw/"
        }
      ]
    },
    team2: {
      key: "team2",
      label: "2. Mannschaft",
      eyebrow: "Herren II",
      heroTitle: "Spielerkarten und Aufstellung.",
      heroLead: "Der Kader basiert auf der FuPa-Teamseite des TSV Hainsfarth II, Stand 2026-07-06. Hier sieht man Spieler, Trainerteam und alle Daten gesammelt auf einer eigenen Seite.",
      heroBadge: "Herren II",
      seasonLabel: "Kader 2025/2026",
      seasonNote: "Mit Spielerkarten und Staff der zweiten Mannschaft.",
      sourceDate: "2026-07-06",
      sourceLabel: "FuPa-Teamseite TSV Hainsfarth II",
      sourceUrl: "https://www.fupa.net/team/tsv-hainsfarth-m2-2025-26",
      sectionEyebrow: "Herren II Kader",
      sectionTitle: "Alle Spieler auf einen Blick",
      sectionLead: "Alle Spielerkarten der zweiten Mannschaft auf einen Blick mit Foto, Position und Leistungsdaten.",
      competition: "Kreisliga Nord Res.",
      players: [
        {
          id: 22918365,
          slug: "nv-yannic-bederke-1578512",
          firstName: "Yannic",
          lastName: "Bederke",
          position: "Torwart",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 24,
          imageUrl: "https://image.fupa.net/player/1FzEc8cJ5nbe/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918351,
          slug: "tobias-hoffmann-446453",
          firstName: "Tobias",
          lastName: "Hoffmann",
          position: "Torwart",
          jerseyNumber: 22,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/UkSdfSE85OZX/",
          yellowCards: 1,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 1
        },
        {
          id: 22918374,
          slug: "nv-daniel-neuf-2013794",
          firstName: "Daniel",
          lastName: "Neuf",
          position: "Torwart",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/UwoPq0Eo8950/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918361,
          slug: "martin-bauer-25332",
          firstName: "Martin",
          lastName: "Bauer",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/pzGb0PGI24aM/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918364,
          slug: "nv-jakob-friedel-2188491",
          firstName: "Jakob",
          lastName: "Friedel",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 19,
          imageUrl: "https://image.fupa.net/player/tgn1Zjs4AiPh/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918363,
          slug: "sven-grosshauser-2188489",
          firstName: "Sven",
          lastName: "Großhauser",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [],
          age: 19,
          imageUrl: "https://image.fupa.net/player/f9p8kcYelk8b/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918372,
          slug: "stefan-randi-180196",
          firstName: "Stefan",
          lastName: "Randi",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/2lJhGKIJi51y/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918355,
          slug: "michael-seitz-179998",
          firstName: "Michael",
          lastName: "Seitz",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 36,
          imageUrl: "https://image.fupa.net/player/xsLtdyId1huZ/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918377,
          slug: "reinhard-steinhoff-2426849",
          firstName: "Reinhard",
          lastName: "Steinhoff",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 3,
          goals: 1,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/PVoBA3Y0y8ix/",
          yellowCards: 2,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918350,
          slug: "markus-strassner-979156",
          firstName: "Markus",
          lastName: "Straßner",
          position: "Abwehr",
          jerseyNumber: 13,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/K1kBuOat6XFS/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918367,
          slug: "nv-daniel-taglieber-955583",
          firstName: "Daniel",
          lastName: "Taglieber",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 27,
          imageUrl: "https://image.fupa.net/player/VEEUAj0mMeo3/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918376,
          slug: "luis-tremmel-2365356",
          firstName: "Luis",
          lastName: "Tremmel",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/3FcWKCuQ3oSk/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 24217078,
          slug: "simon-wiedemann-1913958",
          firstName: "Simon",
          lastName: "Wiedemann",
          position: "Abwehr",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: 22,
          imageUrl: "https://image.fupa.net/player/edroiFk1cyLu/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918356,
          slug: "silvan-egner-485772",
          firstName: "Silvan",
          lastName: "Egner",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/rdu8ocLq0xrB/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918357,
          slug: "maximilian-haas-1788604",
          firstName: "Maximilian",
          lastName: "Haas",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [],
          age: 23,
          imageUrl: "https://image.fupa.net/player/sWpostsVsvgB/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918366,
          slug: "nico-hensolt-108824",
          firstName: "Nico",
          lastName: "Hensolt",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/UvsX5ItV5EjK/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918349,
          slug: "silvan-hertle-179994",
          firstName: "Silvan",
          lastName: "Hertle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 1,
          assists: 0,
          flags: [],
          age: 40,
          imageUrl: "https://image.fupa.net/player/xioCZmDrN9Ry/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918371,
          slug: "nv-enrike-just-2193316",
          firstName: "Enrike",
          lastName: "Just",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 20,
          imageUrl: "https://image.fupa.net/player/2XXzSq8yq06t/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918375,
          slug: "tolga-kahveci-78585",
          firstName: "Tolga",
          lastName: "Kahveci",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 29,
          imageUrl: "https://image.fupa.net/player/yATiDSchGz4n/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918379,
          slug: "nico-leister-179995",
          firstName: "Nico",
          lastName: "Leister",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 30,
          imageUrl: "https://image.fupa.net/player/NHGZwWK7iTIZ/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918380,
          slug: "matthias-marx-1639593",
          firstName: "Matthias",
          lastName: "Marx",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: 24,
          imageUrl: "https://image.fupa.net/player/1ythLl3TRhE4/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918360,
          slug: "hannes-meyer-2071267",
          firstName: "Hannes",
          lastName: "Meyer",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/tltkA3rh9xOJ/",
          yellowCards: 1,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 1
        },
        {
          id: 22918354,
          slug: "nv-daniel-oesterle-175821",
          firstName: "Daniel",
          lastName: "Oesterle",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 37,
          imageUrl: "https://image.fupa.net/player/GYLDnPyJEvgm/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918358,
          slug: "nv-stefan-reichert-490745",
          firstName: "Stefan",
          lastName: "Reichert",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 34,
          imageUrl: "https://image.fupa.net/player/OWGsZeMRx9fC/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918353,
          slug: "leon-seefried-1310773",
          firstName: "Leon",
          lastName: "Seefried",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/AYVVnG7hPQJW/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918373,
          slug: "garibaldi-ueschner-2346918",
          firstName: "Garibaldi",
          lastName: "Üschner",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: null,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918368,
          slug: "nv-daniel-wiedemann-2240298",
          firstName: "Daniel",
          lastName: "Wiedemann",
          position: "Mittelfeld",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 27,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918362,
          slug: "nv-jonas-babel-2188485",
          firstName: "Jonas",
          lastName: "Babel",
          position: "Angriff",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 26,
          imageUrl: "https://image.fupa.net/player/oyp9R2gd1iXL/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918352,
          slug: "jannik-gramm-497501",
          firstName: "Jannik",
          lastName: "Gramm",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 1,
          assists: 0,
          flags: [],
          age: 28,
          imageUrl: "https://image.fupa.net/player/96zo0sWPSF2n/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918369,
          slug: "johannes-gruen-2240299",
          firstName: "Johannes",
          lastName: "Grün",
          position: "Angriff",
          jerseyNumber: null,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: 21,
          imageUrl: "https://image.fupa.net/player/kEhGlJIy7VaA/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 1
        },
        {
          id: 22918370,
          slug: "daniel-hensolt-112807",
          firstName: "Daniel",
          lastName: "Hensolt",
          position: "Angriff",
          jerseyNumber: null,
          matches: 0,
          goals: 0,
          assists: 0,
          flags: [],
          age: 33,
          imageUrl: "https://image.fupa.net/player/RZs3hqECiXOK/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 22918378,
          slug: "simon-meyer-2438423",
          firstName: "Simon",
          lastName: "Meyer",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [],
          age: 22,
          imageUrl: "https://image.fupa.net/player/Y1NfDiFUnwcn/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        },
        {
          id: 24181783,
          slug: "milos-pesut-1130534",
          firstName: "Milos",
          lastName: "Pesut",
          position: "Angriff",
          jerseyNumber: null,
          matches: 1,
          goals: 0,
          assists: 0,
          flags: [
            "new"
          ],
          age: null,
          imageUrl: "https://image.fupa.net/player/6pxKXYYOFU0I/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0,
          hideImage: true
        },
        {
          id: 22918359,
          slug: "christoph-seitz-293972",
          firstName: "Christoph",
          lastName: "Seitz",
          position: "Angriff",
          jerseyNumber: 14,
          matches: 2,
          goals: 0,
          assists: 0,
          flags: [],
          age: 32,
          imageUrl: "https://image.fupa.net/player/9Y7qdRHRTSTj/",
          yellowCards: 0,
          yellowRedCards: 0,
          redCards: 0,
          teamOfWeek: 0
        }
      ],
      staff: [
        {
          id: 22918346,
          slug: "daniel-fackler-446463",
          firstName: "Daniel",
          lastName: "Fackler",
          role: "Trainer",
          age: 32,
          imageUrl: "https://image.fupa.net/player/Ge1tFpMwYc6M/"
        },
        {
          id: 22918347,
          slug: "stefan-randi-180196",
          firstName: "Stefan",
          lastName: "Randi",
          role: "Trainer",
          age: 33,
          imageUrl: "https://image.fupa.net/player/2lJhGKIJi51y/"
        },
        {
          id: 22918348,
          slug: "nv-antonio-aglieri-rinella-362054",
          firstName: "Antonio",
          lastName: "Aglieri Rinella",
          role: "Physiotherapeut",
          age: null,
          imageUrl: "https://image.fupa.net/player/0Ea1kC8iBMZv/"
        }
      ]
    }
  }
};
